export const axios_matrix_sample = [
  {
    adult: false,
    backdrop_path: '/8K9qHeM6G6QjQN0C5XKFGvK5lzM.jpg',
    id: 603,
    title: 'The Matrix',
    original_language: 'en',
    original_title: 'The Matrix',
    overview:
      'Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.',
    poster_path: '/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    media_type: 'movie',
    genre_ids: [28, 878],
    popularity: 87.971,
    release_date: '1999-03-31',
    video: false,
    vote_average: 8.214,
    vote_count: 24595,
  },
  {
    adult: false,
    backdrop_path: '/eNI7PtK6DEYgZmHWP9gQNuff8pv.jpg',
    id: 624860,
    title: 'The Matrix Resurrections',
    original_language: 'en',
    original_title: 'The Matrix Resurrections',
    overview:
      "Plagued by strange memories, Neo's life takes an unexpected turn when he finds himself back inside the Matrix.",
    poster_path: '/8c4a8kE7PizaGQQnditMmI1xbRp.jpg',
    media_type: 'movie',
    genre_ids: [878, 28, 12],
    popularity: 69.889,
    release_date: '2021-12-16',
    video: false,
    vote_average: 6.443,
    vote_count: 5340,
  },
  {
    adult: false,
    backdrop_path: '/pxK1iK6anS6erGg4QePmMKbB1E7.jpg',
    id: 604,
    title: 'The Matrix Reloaded',
    original_language: 'en',
    original_title: 'The Matrix Reloaded',
    overview:
      "Six months after the events depicted in The Matrix, Neo has proved to be a good omen for the free humans, as more and more humans are being freed from the matrix and brought to Zion, the one and only stronghold of the Resistance.  Neo himself has discovered his superpowers including super speed, ability to see the codes of the things inside the matrix and a certain degree of pre-cognition. But a nasty piece of news hits the human resistance: 250,000 machine sentinels are digging to Zion and would reach them in 72 hours. As Zion prepares for the ultimate war, Neo, Morpheus and Trinity are advised by the Oracle to find the Keymaker who would help them reach the Source.  Meanwhile Neo's recurrent dreams depicting Trinity's death have got him worried and as if it was not enough, Agent Smith has somehow escaped deletion, has become more powerful than before and has fixed Neo as his next target.",
    poster_path: '/9TGHDvWrqKBzwDxDodHYXEmOE6J.jpg',
    media_type: 'movie',
    genre_ids: [12, 28, 53, 878],
    popularity: 50.477,
    release_date: '2003-05-15',
    video: false,
    vote_average: 7.044,
    vote_count: 10474,
  },
  {
    adult: false,
    backdrop_path: '/533xAMhhVyjTy8hwMUFEt5TuDfR.jpg',
    id: 605,
    title: 'The Matrix Revolutions',
    original_language: 'en',
    original_title: 'The Matrix Revolutions',
    overview:
      'The human city of Zion defends itself against the massive invasion of the machines as Neo fights to end the war at another front while also opposing the rogue Agent Smith.',
    poster_path: '/qEWiBXJGXK28jGBAm8oFKKTB0WD.jpg',
    media_type: 'movie',
    genre_ids: [12, 28, 53, 878],
    popularity: 46.84,
    release_date: '2003-11-05',
    video: false,
    vote_average: 6.717,
    vote_count: 9448,
  },
  {
    adult: false,
    backdrop_path: '/lAdR6GvEP2o5AM9hWbzVRHCg3RD.jpg',
    id: 116501,
    name: 'Escape The Matrix',
    original_language: 'en',
    original_name: 'Escape The Matrix',
    overview:
      'You cannot escape the matrix unless you know you are in it. Join David Icke as he unravels the nature of the reality that we have been taught to believe is truth, through a lifetime of deep programming.',
    poster_path: '/ur6GSomJqsmpkY16zvXi4q9CtRK.jpg',
    media_type: 'tv',
    genre_ids: [99],
    popularity: 9.462,
    first_air_date: '2020-07-01',
    vote_average: 0,
    vote_count: 0,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/lBdXACywnLwKUZmZkZ87djDQBeV.jpg',
    id: 14543,
    title: 'The Matrix Revisited',
    original_language: 'en',
    original_title: 'The Matrix Revisited',
    overview:
      'The film goes behind the scenes of the 1999 sci-fi movie The Matrix.',
    poster_path: '/8yxSztoc5sqZiGuKcFuVOh65B6Y.jpg',
    media_type: 'movie',
    genre_ids: [99],
    popularity: 16.224,
    release_date: '2001-11-19',
    video: false,
    vote_average: 6.83,
    vote_count: 188,
  },
  {
    adult: false,
    backdrop_path: null,
    id: 221495,
    title: 'The Matrix Recalibrated',
    original_language: 'en',
    original_title: 'The Matrix Recalibrated',
    overview:
      'The making of Matrix Revolutions, The (2003) is briefly touched on here in this documentary. Interviews with various cast and crew members inform us how they were affected by the deaths of Gloria Foster and Aaliyah, and also delve into the making of the visual effects that takes up a lot of screen time. Written by Rhyl Donnelly',
    poster_path: '/gRni1Q651AZPnLqZczmahiIxG0s.jpg',
    media_type: 'movie',
    genre_ids: [99, 878],
    popularity: 6.174,
    release_date: '2004-04-06',
    video: true,
    vote_average: 6.596,
    vote_count: 46,
  },
  {
    adult: false,
    backdrop_path: null,
    id: 503880,
    title: 'The Matrix Revolutions Revisited',
    original_language: 'en',
    original_title: 'The Matrix Revolutions Revisited',
    overview:
      'The making of The Matrix Revolutions:  The cataclysmic final confrontation chronicled through six documentary pods revealing 28 featurettes',
    poster_path: '/61ASnmqvzpuz9VEfFElo3e2nIft.jpg',
    media_type: 'movie',
    genre_ids: [99],
    popularity: 3.285,
    release_date: '2004-12-07',
    video: true,
    vote_average: 7.1,
    vote_count: 22,
  },
  {
    adult: false,
    backdrop_path: '/2WtGZrNxYItKG8Sh518fpUhJTJJ.jpg',
    id: 1223598,
    title: 'Free Your Mind: The Matrix Now',
    original_language: 'en',
    original_title: 'Free Your Mind: The Matrix Now',
    overview:
      'Experience the classic sci-fi film The Matrix like never before in this spectacular live show brought to life through mind-expanding dance and the latest immersive design.',
    poster_path: '/qghosGZ6NGpaQYzgnClQm4lBPJj.jpg',
    media_type: 'movie',
    genre_ids: [10770],
    popularity: 2.846,
    release_date: '2023-12-31',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/5nxDn3mrdmeUHJOZi1Wfqya8Vji.jpg',
    id: 696109,
    title: 'A Glitch in the Matrix',
    original_language: 'en',
    original_title: 'A Glitch in the Matrix',
    overview:
      'Are we in fact living in a simulation? This is the question postulated, wrestled with, and ultimately argued for through archival footage, compelling interviews with real people shrouded in digital avatars, and a collection of cases from some of our most iconoclastic figures in contemporary culture.',
    poster_path: '/bn0BLVadmvzq6MmJ0n97MLxGpNQ.jpg',
    media_type: 'movie',
    genre_ids: [99],
    popularity: 9.196,
    release_date: '2021-02-05',
    video: false,
    vote_average: 4.955,
    vote_count: 33,
  },
  {
    adult: false,
    backdrop_path: null,
    id: 684431,
    title: "Making 'The Matrix'",
    original_language: 'en',
    original_title: "Making 'The Matrix'",
    overview:
      "A promotional making-of documentary for the film Matrix, The (1999) that devotes its time to explaining the digital and practical effects contained in the film. This is very interesting, seeing as how they're giving away the cinematic secrets that they created solely for the this movie, that have now been spoofed and referenced in countless other films.",
    poster_path: '/m2yIfRJYwpCgHON1Ig1pNKMWTxp.jpg',
    media_type: 'movie',
    genre_ids: [99],
    popularity: 2.26,
    release_date: '1999-09-21',
    video: false,
    vote_average: 7.417,
    vote_count: 24,
  },
  {
    adult: false,
    backdrop_path: null,
    id: 591955,
    title: 'The Matrix Reloaded Revisited',
    original_language: 'en',
    original_title: 'The Matrix Reloaded Revisited',
    overview:
      "The making of The Matrix Reloaded:  Go to the middle movie's furthest reaches via five documentary paths revealing 21 featurettes.",
    poster_path: '/gb7C4oRzYWXWCuZMR1cwtHa53Pz.jpg',
    media_type: 'movie',
    genre_ids: [99],
    popularity: 4.631,
    release_date: '2004-12-07',
    video: true,
    vote_average: 6.6,
    vote_count: 26,
  },
  {
    adult: false,
    backdrop_path: null,
    id: 684731,
    title: 'The Matrix Reloaded: Pre-Load',
    original_language: 'en',
    original_title: 'The Matrix Reloaded: Pre-Load',
    overview:
      'This making-of piece offers the standard mix of movie snippets, behind the scenes materials, and interviews from cast and crew on the making of the film.',
    poster_path: null,
    media_type: 'movie',
    genre_ids: [99],
    popularity: 2.933,
    release_date: '2003-10-14',
    video: false,
    vote_average: 6,
    vote_count: 18,
  },
  {
    adult: false,
    backdrop_path: null,
    id: 274866,
    title: 'The Roots of the Matrix',
    original_language: 'en',
    original_title: 'The Roots of the Matrix',
    overview:
      "Disc 8 of 10 of 'The Matrix: Ultimate Edition': Probe the philosophical and technological inspirations of The Matrix Trilogy through two insightful documentaries:  - Return to Source: Philosophy &amp; The Matrix documentary – Scholars, philosophers and theorists deconstruct the intellectual underpinnings of the trilogy  - The Hard Problem: The Science Behind the Fiction documentary – Is the notion of a real Matrix plausible? An investigation of the technologies that inspire the metaphor of the Matrix.",
    poster_path: '/qmOtnpPihV3Wj6ukpiNIgzo4Ax7.jpg',
    media_type: 'movie',
    genre_ids: [99],
    popularity: 1.203,
    release_date: '2004-12-07',
    video: false,
    vote_average: 7,
    vote_count: 3,
  },
  {
    adult: false,
    backdrop_path: null,
    id: 684428,
    title: 'The Matrix: What Is Bullet-Time?',
    original_language: 'en',
    original_title: 'The Matrix: What Is Bullet-Time?',
    overview:
      'Special Effects wizard John Gaeta demonstrates how the "Bullet-Time" effects were created for the film Matrix, The (1999).',
    poster_path: '/hSTervHaROcTd8Ir3DPfepN80dL.jpg',
    media_type: 'movie',
    genre_ids: [99, 28, 878],
    popularity: 3.291,
    release_date: '1999-09-21',
    video: false,
    vote_average: 5.3,
    vote_count: 10,
  },
  {
    adult: false,
    backdrop_path: null,
    id: 684740,
    title: 'The Matrix Revolutions: Neo Realism - Evolution of Bullet Time',
    original_language: 'en',
    original_title:
      'The Matrix Revolutions: Neo Realism - Evolution of Bullet Time',
    overview: 'A featurette about the special effects of The Matrix Trilogy',
    poster_path: '/2US7uuM36El9pnk8WLdGh1XN39r.jpg',
    media_type: 'movie',
    genre_ids: [99],
    popularity: 3.69,
    release_date: '2004-04-06',
    video: false,
    vote_average: 6.5,
    vote_count: 12,
  },
  {
    adult: false,
    backdrop_path: '/b3toMttpZ0cFeYMgLeL042uJJpi.jpg',
    id: 684735,
    title: "Making 'Enter the Matrix'",
    original_language: 'en',
    original_title: "Making 'Enter the Matrix'",
    overview:
      "A look at Enter the Matrix: The game's story picks up just before The Matrix Reloaded and runs parallel to that of the film. Bend the rules of the Matrix with martial arts, pilot the fastest hovercraft in the fleet, or just fight with lots of guns.",
    poster_path: '/zQbJkJkzpB8EthEJ3r2Y6A2kkP6.jpg',
    media_type: 'movie',
    genre_ids: [99, 28, 878],
    popularity: 0.976,
    release_date: '2003-10-14',
    video: false,
    vote_average: 5.1,
    vote_count: 7,
  },
  {
    adult: false,
    backdrop_path: null,
    id: 174615,
    title: 'Return to Source: The Philosophy of The Matrix',
    original_language: 'en',
    original_title: 'Return to Source: The Philosophy of The Matrix',
    overview:
      'An hour long discussion on the philosophical concepts that inspired, and are presented in the trilogy. This is one of the two feature-length documentaries on disc number 8 of the 10-Disc Ultimate Set.',
    poster_path: '/8y6mcZbXxL0IIV4GJJ4whLwApow.jpg',
    media_type: 'movie',
    genre_ids: [99],
    popularity: 1.927,
    release_date: '2004-12-07',
    video: false,
    vote_average: 7,
    vote_count: 14,
  },
  {
    adult: false,
    backdrop_path: null,
    id: 684729,
    title: 'The Matrix Reloaded: Car Chase',
    original_language: 'en',
    original_title: 'The Matrix Reloaded: Car Chase',
    overview:
      "This thirty-minute documentary follows the Wachowski sisters and the film's crew through production on the film's famed highway chase sequence. We get interviews with the visual effects supervisors, the stunt coordinators and even are taken through aspects of pre-production and planning for the scene. Then the documentary moves into production, the scariest aspect of which is certainly Carrie Anne-Moss trying to learn to ride a motorcycle good enough to do so safely without helmet for the scene. We also watch as the stretch of freeway used in the film is being built.",
    poster_path: '/zkpzfTyF7BjadH1PZKlC6kueWXf.jpg',
    media_type: 'movie',
    genre_ids: [99, 28, 878],
    popularity: 1.594,
    release_date: '2004-12-07',
    video: false,
    vote_average: 6.5,
    vote_count: 6,
  },
  {
    adult: false,
    backdrop_path: '/1wdULm68hAqRwaQH9GuVcGO430e.jpg',
    id: 850111,
    title: 'Delusions End: Breaking Free of the Matrix',
    original_language: 'en',
    original_title: 'Delusions End: Breaking Free of the Matrix',
    overview:
      'In a world of lies and deception and false hopes, the time is now to remove the blinders of deception and take back our lives.',
    poster_path: '/5sfH0dXcRrzMmuQ7tBdQl0n9PXv.jpg',
    media_type: 'movie',
    genre_ids: [99],
    popularity: 0.915,
    release_date: '2021-07-13',
    video: false,
    vote_average: 2,
    vote_count: 1,
  },
];
export const axios_demon_sample = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/9mrSx9MVmNOOlvcPxDTdf1APzud.jpg',
      id: 1216221,
      title: 'Demon Slayer: Kimetsu no Yaiba -To the Hashira Training-',
      original_language: 'ja',
      original_title: '「鬼滅の刃」絆の奇跡、そして柱稽古へ',
      overview:
        'A compilation film featuring the eleventh episode of the Swordsmith Village Arc and the first episode of the Hashira Training Arc.',
      poster_path: '/3daOEMQCOGU2n9EbUC0PICnUCek.jpg',
      media_type: 'movie',
      genre_ids: [16, 28, 14],
      popularity: 1960.887,
      release_date: '2024-02-02',
      video: true,
      vote_average: 5.846,
      vote_count: 91,
    },
    {
      adult: false,
      backdrop_path: '/nTvM4mhqNlHIvUkI1gVnW6XP7GG.jpg',
      id: 85937,
      name: 'Demon Slayer: Kimetsu no Yaiba',
      original_language: 'ja',
      original_name: '鬼滅の刃',
      overview:
        'It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself. Though devastated by this grim reality, Tanjiro resolves to become a “demon slayer” so that he can turn his sister back into a human, and kill the demon that massacred his family.',
      poster_path: '/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg',
      media_type: 'tv',
      genre_ids: [16, 10759, 10765],
      popularity: 121.819,
      first_air_date: '2019-04-06',
      vote_average: 8.7,
      vote_count: 5929,
      origin_country: ['JP'],
    },
    {
      adult: false,
      backdrop_path: '/daeD5T4MxFk5MppZlaNZoaK6lE9.jpg',
      id: 811948,
      title: 'Demon Slayer: Kimetsu no Yaiba the Hashira Meeting Arc',
      original_language: 'ja',
      original_title: '鬼滅の刃 柱合会議・蝶屋敷編',
      overview:
        'Tanjiro and his sister Nezuko have been apprehended by the Demon Slayer Hashira, a group of extremely skilled swordfighters. Tanjiro undergoes trial for violating the Demon Slayer code, specifically smuggling Nezuko, a Demon, onto Mt. Natagumo. A recap film of Kimetsu no Yaiba, covering episodes 22-26 with some new footage and special ending credits.',
      poster_path: '/iTmJwZxGHYAk5EiVc68UvZTMSuP.jpg',
      media_type: 'movie',
      genre_ids: [16, 14],
      popularity: 147.882,
      release_date: '2021-04-15',
      video: true,
      vote_average: 7,
      vote_count: 225,
    },
    {
      adult: false,
      backdrop_path: '/tcYO8ay3A0liCWxHu2creU3Q9IB.jpg',
      id: 1067282,
      title: 'Demon Slayer: Kimetsu no Yaiba -To the Swordsmith Village-',
      original_language: 'ja',
      original_title: '「鬼滅の刃」上弦集結、そして刀鍛冶の里へ',
      overview:
        'After his family is viciously murdered, a kind-hearted boy named Tanjiro Kamado resolves to become a Demon Slayer in hopes of turning his younger sister Nezuko back into a human.  Together with his comrades, Zenitsu and Inosuke, along with one of the top-ranking members of the Demon Slayer Corps, Tengen Uzui, Tanjiro embarks on a mission within the Entertainment District, where they encounter the formidable, high-ranking demons, Daki and Gyutaro.',
      poster_path: '/hEhGrcST85vMd63PBDgPBqih2tR.jpg',
      media_type: 'movie',
      genre_ids: [28, 16, 14],
      popularity: 113.47,
      release_date: '2023-02-03',
      video: true,
      vote_average: 7.4,
      vote_count: 337,
    },
    {
      adult: false,
      backdrop_path: '/qjGrUmKW78MCFG8PTLDBp67S27p.jpg',
      id: 635302,
      title: 'Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train',
      original_language: 'ja',
      original_title: '劇場版「鬼滅の刃」無限列車編',
      overview:
        "Tanjiro Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyojuro Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!",
      poster_path: '/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg',
      media_type: 'movie',
      genre_ids: [28, 16, 12, 14, 53],
      popularity: 121.781,
      release_date: '2020-10-16',
      video: false,
      vote_average: 8.231,
      vote_count: 3634,
    },
    {
      adult: false,
      backdrop_path: null,
      id: 1242810,
      title: 'Stage Play "Demon Slayer: Kimetsu no Yaiba"',
      original_language: 'ja',
      original_title: '舞台「鬼滅の刃」',
      overview:
        'The official stage play adaptation of Koyoharu Gotoge\'s series Kimetsu no Yaiba. The time is Taisho, Japan. One day, Tanjiro, a kind-hearted boy who sells charcoal, has his entire family killed by a demon. Furthermore, his only surviving sister, Nezuko, has been transformed into a demon. Tanjiro is devastated by the hopeless reality, but decides to pursue the path of "demon hunting" in order to return his sister to a human and avenge the demon that killed his family. The sad story of brother and sister, woven together by humans and demons, begins now!',
      poster_path: '/dsnQGgYLhAGhWhgrVC2RMcMYIHn.jpg',
      media_type: 'movie',
      genre_ids: [],
      popularity: 40.961,
      release_date: '2020-02-02',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/8NEvnVKeGMLEXG45MMNqxJLcM4y.jpg',
      id: 820232,
      title: "Demon Slayer: Kimetsu no Yaiba Sibling's Bond",
      original_language: 'ja',
      original_title: '鬼滅の刃 兄妹の絆',
      overview:
        "Tanjiro finds his family slaughtered and the lone survivor, his sister Nezuko Kamado, turned into a Demon. To his surprise, however, Nezuko still shows signs of human emotion and thought. Thus begins Tanjiro's journey to seek out the Demon who killed their family and turn his sister human again. A recap film of Kimetsu no Yaiba, covering episodes 1-5 with extra footage.",
      poster_path: '/vJUDoYNNKvBqbEPUskgvzPXGEFz.jpg',
      media_type: 'movie',
      genre_ids: [28, 16, 14],
      popularity: 89.968,
      release_date: '2019-03-29',
      video: false,
      vote_average: 7.93,
      vote_count: 185,
    },
    {
      adult: false,
      backdrop_path: '/kRlqWz54iI9K1PjI15cwvtHjnSw.jpg',
      id: 802401,
      title: 'Demon Slayer: Kimetsu no Yaiba Mt. Natagumo Arc',
      original_language: 'ja',
      original_title: '鬼滅の刃 那田蜘蛛山編',
      overview:
        'Tanjiro, now a registered Demon Slayer, teams up with fellow slayers Zenitsu and Inosuke to investigate missing person cases on the mountain Natagumo. After the group is split up during a fight with possessed swordfighters, they slowly begin to realize the entire mountain is being controlled by a family of Demon spider creatures.  A recap film of Kimetsu no Yaiba, covering episodes 15-21 with some new footage and special ending credits.',
      poster_path: '/wq1UG5lPCKpOJgmgpKJszKvoMUe.jpg',
      media_type: 'movie',
      genre_ids: [28, 16, 18, 14, 12],
      popularity: 83.984,
      release_date: '2021-04-15',
      video: true,
      vote_average: 7.918,
      vote_count: 208,
    },
    {
      adult: false,
      backdrop_path: '/cqI5ZpzesnxaRqi7OCAT0C2uqg0.jpg',
      id: 895006,
      title: 'Demon Slayer: Kimetsu no Yaiba - Tsuzumi Mansion Arc',
      original_language: 'ja',
      original_title: '鬼滅の刃 鼓屋敷編',
      overview:
        'Tanjiro ventures to the south-southeast where he encounters a cowardly young man named Zenitsu Agatsuma. He is a fellow survivor from Final Selection and his sparrow asks Tanjiro to help keep him in line.',
      poster_path: '/2yiDQCDj7hlq2SwLojV9xrFkCnr.jpg',
      media_type: 'movie',
      genre_ids: [16, 28, 14],
      popularity: 59.18,
      release_date: '2022-09-15',
      video: true,
      vote_average: 7.533,
      vote_count: 122,
    },
    {
      adult: false,
      backdrop_path: '/6EUCHkb3rmqy08EP07oMPZbjpZR.jpg',
      id: 895003,
      title: 'Demon Slayer: Kimetsu no Yaiba - Asakusa Arc',
      original_language: 'ja',
      original_title: '鬼滅の刃 浅草編',
      overview:
        'Tanjiro ventures to Asakusa, Tokyo for his second mission with the Demon Slayer Corps.',
      poster_path: '/t2w332ARBJxy1G65abj8C7VNjeW.jpg',
      media_type: 'movie',
      genre_ids: [16, 14],
      popularity: 50.811,
      release_date: '2022-08-25',
      video: true,
      vote_average: 7.873,
      vote_count: 51,
    },
    {
      adult: false,
      backdrop_path: '/pX0V3SmElE76KBpoYg1A9QcXCR3.jpg',
      id: 95993,
      title: 'Demon Slayer',
      original_language: 'en',
      original_title: 'Demon Slayer',
      overview:
        'Five delinquent teenagers are assigned the task of converting a long-abandoned mental hospital in South Central Los Angeles into a community center. Little do they know that the hospital is the site of centuries of supernatural mayhem and murder. Plagued by terrors beyond belief, the teenagers must fight to survive a battle where the division between the living and the dead is shattered.',
      poster_path: '/wFeHHxnTrSb4NaFRqFDYcqtqbQ1.jpg',
      media_type: 'movie',
      genre_ids: [27],
      popularity: 8.063,
      release_date: '2003-02-20',
      video: false,
      vote_average: 7.3,
      vote_count: 15,
    },
    {
      adult: false,
      backdrop_path: '/fpZWYU5HfU3YiFlhNiTBfEJrTDB.jpg',
      id: 40171,
      title: 'Woochi: The Demon Slayer',
      original_language: 'ko',
      original_title: '전우치',
      overview:
        'Spanning four centuries in Korea, this epic action-adventure concerns a powerful pipe and a trio of wizards who will do anything to protect it.',
      poster_path: '/xrgsXvKv8h2X5xbZduJK6cMxtfE.jpg',
      media_type: 'movie',
      genre_ids: [12, 28, 35, 14],
      popularity: 18.483,
      release_date: '2009-12-23',
      video: false,
      vote_average: 6.591,
      vote_count: 115,
    },
    {
      adult: false,
      backdrop_path: '/tTqFu88ef79Y9WcdoBGF9xKmNao.jpg',
      id: 452910,
      title: 'Immortal Demon Slayer',
      original_language: 'zh',
      original_title: '悟空傳',
      overview:
        'The story tells the story of Sun Wukong and Erlang Shen, who come to the Immortal Mountain to cultivate their skills. They gain friendship, experience love and ultimately betrayal, growing throughout their life journey.',
      poster_path: '/hbqM7RnXlGO0dFXqMlJYc7z703p.jpg',
      media_type: 'movie',
      genre_ids: [14, 28, 12],
      popularity: 23.911,
      release_date: '2017-07-13',
      video: false,
      vote_average: 7.534,
      vote_count: 146,
    },
    {
      adult: false,
      backdrop_path: '/v8POi1zZl9oYloab5LiFZ8EK432.jpg',
      id: 1141171,
      title: 'Demon Slayer: Kimetsu no Yaiba ON STAGE',
      original_language: 'ja',
      original_title: 'Demon Slayer: Kimetsu no Yaiba ON STAGE',
      overview:
        "A special stage program celebrating the series of the Demon Slayer: Kimetsu no Yaiba anime. This stage program is a live capture and features cast members who bring the series' world to life, as they perform an exclusive live reading of an original story and a special live dubbing performance.",
      poster_path: '/dwuVipGiAfGZ3SAOJClm6bweUts.jpg',
      media_type: 'movie',
      genre_ids: [],
      popularity: 33.965,
      release_date: '2023-07-18',
      video: true,
      vote_average: 4.8,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: '/1OLbvl1M23nU2NzLaLYXEvdYTUW.jpg',
      id: 39880,
      title: 'Sakuya: The Slayer of Demons',
      original_language: 'ja',
      original_title: 'さくや 妖怪伝',
      overview:
        'The eruption of Mt. Fuji in 1707 released hordes of demons from deep inside the earth. Sakuya, the young daughter of a samurai killed fighting these demons, accepts a mission to travel to Mt. Fuji and defeat the evil spirits. Accompanying her on her journey are two veteran warriors who served her father, and Tarō, a young kappa, or river spirit, whom she has adopted as her little brother. Along the way, the two warriors have doubts about Tarō’s loyalties, and the young kappa himself must decide if he will stand with his own species or with the humans who have cared for him.',
      poster_path: '/G2lJyqPDgwOloRmaeut0sSHRFR.jpg',
      media_type: 'movie',
      genre_ids: [12, 14],
      popularity: 7.845,
      release_date: '2000-12-08',
      video: false,
      vote_average: 6.1,
      vote_count: 8,
    },
    {
      adult: false,
      backdrop_path: null,
      id: 1187574,
      title: 'Demon Slayer Orchestra Concert-Mugen Train ARC',
      original_language: 'en',
      original_title: 'Demon Slayer Orchestra Concert-Mugen Train ARC',
      overview:
        'Featuring the Tokyo Philharmonic Orchestra, the Demon Slayer concert is the second in the series following a similar event held previously. Fans will be able to enjoy music from the "Demon Slayer: Mugen Train" movie along with animated clips at the showings.',
      poster_path: '/2ucouLI7iSh2xI3MvNmLVKIEKOo.jpg',
      media_type: 'movie',
      genre_ids: [],
      popularity: 13.268,
      release_date: '',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/ek4BlZ4ZCdVannkLz7VYjvWDKZb.jpg',
      id: 887074,
      title: 'The Sword',
      original_language: 'zh',
      original_title: '屠魔：王者征途',
      overview:
        'Lord of Darkness Artha was born from human struggle and resentment. In ancient times he formed an army of undead to conquer the world. At the moment of final battle human leaders used blood to forge the holy sword to seal Artha. For thousands of years, legends have fallen one after another, and Artha has made a comeback.',
      poster_path: '/xUSw4EZApLW0ghZgjGQKMClb8H0.jpg',
      media_type: 'movie',
      genre_ids: [],
      popularity: 10.93,
      release_date: '2021-10-18',
      video: false,
      vote_average: 5.3,
      vote_count: 3,
    },
  ],
  total_pages: 1,
  total_results: 17,
};
